FROM node:20 as build

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm run build -- --configuration production

FROM nginx:alpine

COPY --from=build /app/dist/frontend /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off" ]